//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDKT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Banner
    {
        public int BannerID { get; set; }
        [UIHint("Image")]
        public string UrlImage { get; set; }
        public System.DateTime DateUpload { get; set; }
        public bool IsActive { get; set; }
    }
}
