//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDKT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Image
    {
        public int ImageID { get; set; }
        public string UrlResizeImage { get; set; }
        public string UrlBigImage { get; set; }
        public System.DateTime DateUpload { get; set; }
        public bool IsLibrary { get; set; }
        public Nullable<int> CatalogID { get; set; }
    
        public virtual Catalog Catalog { get; set; }
    }
}
